default_job = "watch"
env.CARGO_TERM_COLOR = "always"

[jobs.watch]
command = ["cargo", "make", "serve"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["pkill", "-INT", "-P"]
watch = ["examples/playground/assets"]
