[workspace]
members = ["examples/playground"]

[package]
name = "twors"
version = "0.1.1"
edition = "2024"
authors = ["Lyudmil Grigorov"]
description = "A simple Rust 2D game engine based on canvas and WASM"
readme = "README.md"
repository = "https://github.com/vimlucid/twors"
license = "MIT"
keywords = ["game", "engine", "2d", "wasm", "canvas"]
categories = ["wasm", "rendering::engine", "graphics", "web-programming", "game-engines"]

[dependencies]
log = "0.4.27"
thiserror = "2.0.12"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["CanvasRenderingContext2d", "Document", "Element", "HtmlCanvasElement", "MouseEvent", "Window"] }
web-time = "1.1.0"
