[package]
name = "twors"
version = "0.1.0"
edition = "2024"
authors = ["Lyudmil Grigorov"]
description = "A simple Rust 2D game engine based on canvas and WASM"
readme = "README.md"
repository = "https://github.com/vimlucid/twors"
license = "MIT"
keywords = ["game", "engine", "2d", "wasm", "canvas"]
categories = ["wasm", "rendering::engine", "graphics", "web-programming", "game-engines"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
