[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build", "clean"]

[tasks.pkg-build]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
command = "wasm-pack"
args = ["build", "--target", "web"]

[tasks.pkg]
command = "cp"
args = ["./assets/index.html", "./pkg"]
dependencies = ["pkg-build"]

[tasks.serve]
install_crate = { crate_name = "miniserve", binary = "miniserve", test_arg = "--help" }
command = "miniserve"
args = ["./pkg", "--index", "index.html"]
dependencies = ["pkg-build"]

[tasks.licenses]
install_crate = { crate_name = "cargo-about", binary = "cargo-about", test_arg = "--help" }
command = "cargo"
args = [
    "about", "generate",
    "--config", "./licenses/about.toml",
    "./licenses/about.hbs",
    "--output-file", "./licenses/licenses.html"
]

