[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build-git-hooks]
command = "cargo"
args = ["build", "--bin", "pre-commit", "--release"]

[tasks.install-git-hooks]
command = "git"
args = ["config", "core.hooksPath", "target/release"]
dependencies = ["build-git-hooks"]

[tasks.build]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
command = "wasm-pack"
args = ["build", "--target", "web"]
dependencies = ["install-git-hooks"]

[tasks.pkg]
command = "cp"
args = ["./assets/index.html", "./pkg"]
dependencies = ["build"]

[tasks.serve]
install_crate = { crate_name = "miniserve", binary = "miniserve", test_arg = "--help" }
command = "miniserve"
args = ["./pkg", "--index", "index.html"]
dependencies = ["pkg"]

[tasks.watch]
install_crate = { crate_name = "bacon", binary = "bacon", test_arg = "--help" }
command = "bacon"
args = ["watch"]

[tasks.licenses]
install_crate = { crate_name = "cargo-about", binary = "cargo-about", test_arg = "--help" }
command = "cargo"
args = [
    "about", "generate",
    "--config", "./licenses/about.toml",
    "./licenses/about.hbs",
    "--output-file", "./licenses/licenses.html"
]
