[package]
name = "playground"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_log = { version = "1.0.0", features = ["color"] }
log = "0.4.27"
twors = { version = "0.4.0", path = "../../" }
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"
